on:
  push:
    branches:
      - master

name: Deploy template app to shinyapps.io

jobs:
  deploy-shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@v4

      - name: 🛠️ Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release' # Utilise la dernière version stable de R

      - name: 📦 Install Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::shiny
            any::rsconnect
            any::httr
            any::jsonlite
            any::leaflet
            any::trend

      - name: 💎 Deploy to shinyapps.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='hydrotrend', token='${{ secrets.TOKEN }}', secret='${{ secrets.SECRET }}')"
          Rscript -e "rsconnect::deployApp(appName='myApp', appDir='.', dependencyResolution='local')"